In [79]:
import pandas as pd 
import numpy as np

In [88]:
df=pd.read_excel(r"E:\部门工作相关\感染性事件\普通患者\IcuNonOperation_BJ_BJ_JQYY_2020_05_19_12___\住院ICU科室名称\数据分析\院内院外感染\院内感染患者计算移动平均.xlsx",sheet_name=1,header=0)
df.head(10)

,RCASEID,CASEID,入院天数,患者年龄,血糖测定值,住院时间,ICU科室时间,ICU病区时间,每日体温最高值,是否发热≥38℃,每日体温最低值,血白细胞,抗菌药物升级,未使用抗菌药物,是否呼吸机,是否留置导尿,是否中心静脉插管,NIS感染
0,CIID1653097869317580163,69243(8),1,83,NaN,1.0,1.0,NaN,37.2,0,37.1,NaN,NaN,0,0,0,0,0
1,CIID1653097869317580163,69243(8),2,83,NaN,NaN,NaN,NaN,37.6,0,36.7,NaN,NaN,0,0,0,0,0
2,CIID1653097869317580163,69243(8),3,83,NaN,NaN,NaN,NaN,37.0,0,36.5,NaN,NaN,0,0,0,0,0
3,CIID1653097869317580163,69243(8),4,83,NaN,NaN,NaN,NaN,38.2,1,37.0,NaN,1.0,0,0,1,0,0
4,CIID1653097869317580163,69243(8),5,83,NaN,NaN,NaN,NaN,38.2,1,36.8,10.06,NaN,0,0,1,0,0
5,CIID1653097869317580163,69243(8),6,83,5.34,NaN,NaN,NaN,37.6,0,36.6,NaN,NaN,0,0,1,0,0
6,CIID1653097869317580163,69243(8),7,83,NaN,NaN,NaN,NaN,37.2,0,36.8,NaN,NaN,0,0,1,0,0
7,CIID1653097869317580163,69243(8),8,83,5.10,NaN,NaN,NaN,36.8,0,36.6,7.47,NaN,0,0,1,0,0
8,CIID1653097869317580163,69243(8),9,83,NaN,NaN,NaN,NaN,36.8,0,36.8,NaN,NaN,0,0,1,0,0
9,CIID1653097869317580163,69243(8),10,83,NaN,NaN,NaN,NaN,36.8,0,36.8,NaN,1.0,0,0,1,0,0

In [89]:
df2=df.drop(['入院天数','CASEID','患者年龄','住院时间','血糖测定值','ICU科室时间','ICU病区时间','血白细胞'],axis=1)

In [90]:
df2.head(5)

,RCASEID,每日体温最高值,是否发热≥38℃,每日体温最低值,抗菌药物升级,未使用抗菌药物,是否呼吸机,是否留置导尿,是否中心静脉插管,NIS感染
0,CIID1653097869317580163,37.2,0,37.1,NaN,0,0,0,0,0
1,CIID1653097869317580163,37.6,0,36.7,NaN,0,0,0,0,0
2,CIID1653097869317580163,37.0,0,36.5,NaN,0,0,0,0,0
3,CIID1653097869317580163,38.2,1,37.0,1.0,0,0,1,0,0
4,CIID1653097869317580163,38.2,1,36.8,NaN,0,0,1,0,0

In [91]:
df2['抗菌药物升级']=df2['抗菌药物升级'].fillna(0)
df2.head(10)

,RCASEID,每日体温最高值,是否发热≥38℃,每日体温最低值,抗菌药物升级,未使用抗菌药物,是否呼吸机,是否留置导尿,是否中心静脉插管,NIS感染
0,CIID1653097869317580163,37.2,0,37.1,0.0,0,0,0,0,0
1,CIID1653097869317580163,37.6,0,36.7,0.0,0,0,0,0,0
2,CIID1653097869317580163,37.0,0,36.5,0.0,0,0,0,0,0
3,CIID1653097869317580163,38.2,1,37.0,1.0,0,0,1,0,0
4,CIID1653097869317580163,38.2,1,36.8,0.0,0,0,1,0,0
5,CIID1653097869317580163,37.6,0,36.6,0.0,0,0,1,0,0
6,CIID1653097869317580163,37.2,0,36.8,0.0,0,0,1,0,0
7,CIID1653097869317580163,36.8,0,36.6,0.0,0,0,1,0,0
8,CIID1653097869317580163,36.8,0,36.8,0.0,0,0,1,0,0
9,CIID1653097869317580163,36.8,0,36.8,1.0,0,0,1,0,0

In [92]:
df2=df2.groupby(['RCASEID']).rolling(28).mean()
df2.head(20)

                               每日体温最高值  是否发热≥38℃  每日体温最低值  抗菌药物升级  未使用抗菌药物  \
RCASEID
CIID1653089778641407901 24680      NaN       NaN      NaN     NaN      NaN
                        24681      NaN       NaN      NaN     NaN      NaN
                        24682      NaN       NaN      NaN     NaN      NaN
                        24683      NaN       NaN      NaN     NaN      NaN
                        24684      NaN       NaN      NaN     NaN      NaN
                        24685      NaN       NaN      NaN     NaN      NaN
                        24686      NaN       NaN      NaN     NaN      NaN
                        24687      NaN       NaN      NaN     NaN      NaN
                        24688      NaN       NaN      NaN     NaN      NaN
                        24689      NaN       NaN      NaN     NaN      NaN
                        24690      NaN       NaN      NaN     NaN      NaN
                        24691      NaN       NaN      NaN     NaN      NaN
                        24692      NaN       NaN      NaN     NaN      NaN
                        24693      NaN       NaN      NaN     NaN      NaN
                        24694      NaN       NaN      NaN     NaN      NaN
                        24695      NaN       NaN      NaN     NaN      NaN
                        24696      NaN       NaN      NaN     NaN      NaN
                        24697      NaN       NaN      NaN     NaN      NaN
CIID1653089847666026189 20472      NaN       NaN      NaN     NaN      NaN
                        20473      NaN       NaN      NaN     NaN      NaN

                               是否呼吸机  是否留置导尿  是否中心静脉插管  NIS感染
RCASEID
CIID1653089778641407901 24680    NaN     NaN       NaN    NaN
                        24681    NaN     NaN       NaN    NaN
                        24682    NaN     NaN       NaN    NaN
                        24683    NaN     NaN       NaN    NaN
                        24684    NaN     NaN       NaN    NaN
                        24685    NaN     NaN       NaN    NaN
                        24686    NaN     NaN       NaN    NaN
                        24687    NaN     NaN       NaN    NaN
                        24688    NaN     NaN       NaN    NaN
                        24689    NaN     NaN       NaN    NaN
                        24690    NaN     NaN       NaN    NaN
                        24691    NaN     NaN       NaN    NaN
                        24692    NaN     NaN       NaN    NaN
                        24693    NaN     NaN       NaN    NaN
                        24694    NaN     NaN       NaN    NaN
                        24695    NaN     NaN       NaN    NaN
                        24696    NaN     NaN       NaN    NaN
                        24697    NaN     NaN       NaN    NaN
CIID1653089847666026189 20472    NaN     NaN       NaN    NaN
                        20473    NaN     NaN       NaN    NaN

In [93]:
df2.to_csv(r"E:\部门工作相关\感染性事件\普通患者\IcuNonOperation_BJ_BJ_JQYY_2020_05_19_12___\住院ICU科室名称\数据分析\院内院外感染\院内感染患者计算移动平均结果28.csv")